GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test blog",
    "author": "Salman Rushdie",
    "url": "www.rushdie.com/test-blog",
    "likes": 10
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test blog - 2",
    "author": "JK Rowling",
    "url": "www.rowling.com/test-blog-2",
    "likes": 20
}


###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZhbGlkYXRvcjEiLCJpZCI6IjY5MWM5NzhkMTA3ZmE4MzA1NWRiOTA0NCIsImlhdCI6MTc2MzU2MTMxNywiZXhwIjoxNzYzNTY0OTE3fQ.gWdUuk6o54gwYjAAlMotpnj4kVXJgNnKEJ8V0VbVrPc

{
    "title": "Test blog - 2",
    "author": "JK Rowling",
    "url": "www.rowling.com/test-blog-2",
    "likes": 20
}

###
DELETE http://localhost:3003/api/blogs/691dd01b1b66adb4dc323a58
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZhbGlkYXRvcjEiLCJpZCI6IjY5MWM5NzhkMTA3ZmE4MzA1NWRiOTA0NCIsImlhdCI6MTc2MzU2MTMxNywiZXhwIjoxNzYzNTY0OTE3fQ.gWdUuk6o54gwYjAAlMotpnj4kVXJgNnKEJ8V0VbVrPc
