POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "validator1",
    "name": "validator number1",
    "password": "abcdval01"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "validator1",
    "name": "validator number1",
    "password": "abcdval01"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "validator2",
    "name": "validator number2",
    "password": "abcdval02"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "v3",
    "name": "validator number3",
    "password": "abcdval03"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "validator3",
    "name": "validator number3",
    "password": "a3"
}

###

GET http://localhost:3003/api/users 

