GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1 

###
GET http://localhost:3001/info 


###
GET http://localhost:3001/api/persons/507f1f77bcf86cd799439011

###
GET http://localhost:3001/api/persons/4

###
DELETE  http://localhost:3001/api/persons/6914acec8eb8f8c924e298c7

###
DELETE  http://localhost:3001/api/persons/507f1f77bcf86cd799439011

###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Chris Rimmer",
    "number": "44-0342343429"
}

###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "44-0342343429"
}


###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Dinesh Sthapit"
}