GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1 

###
GET http://localhost:3001/info 


###
GET http://localhost:3001/api/persons/4

###
DELETE  http://localhost:3001/api/persons/4

###
DELETE  http://localhost:3001/api/persons/5

###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Dinesh Sthapit",
    "number": "44-0342343429"
}

###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "44-0342343429"
}


###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Dinesh Sthapit"
}